### ISSUE TITLE
Development server failed to start

### ISSUE THREAD

**Issue by kamalx** [mathieudutour/svg-path-visualizer#61]
Hello, I found this tool very interesting to learn more about SVG and thus tried to get it running on my machine but I've hit a roadblock on step 0. Not sure if this is the right place to post this (please let me know if there's another place to report such issues) but in the hope that this is something that could eliminate a potential bug, I am just posting the log of the errors I got here:

Full error log
```
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (/home/user/gh-repos/svg-path-visualizer/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/user/gh-repos/svg-path-visualizer/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/user/gh-repos/svg-path-visualizer/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/user/gh-repos/svg-path-visualizer/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/user/gh-repos/svg-path-visualizer/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/user/gh-repos/svg-path-visualizer/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/user/gh-repos/svg-path-visualizer/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/user/gh-repos/svg-path-visualizer/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/home/user/gh-repos/svg-path-visualizer/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (/home/user/gh-repos/svg-path-visualizer/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/user/gh-repos/svg-path-visualizer/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/user/gh-repos/svg-path-visualizer/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/user/gh-repos/svg-path-visualizer/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/user/gh-repos/svg-path-visualizer/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/user/gh-repos/svg-path-visualizer/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/user/gh-repos/svg-path-visualizer/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/user/gh-repos/svg-path-visualizer/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v23.0.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## steps to reproduce for me:

`git clone git@github.com:mathieudutour/svg-path-visualizer.git`
`cd svg-path-visualizer`
`yarn`
`yarn start #fails`

**Comment by mathieudutour** [comment]
it's an old project, some dependencies might be outdated. You can try `NODE_OPTIONS=--openssl-legacy-provider yarn start`
